### ISSUE TITLE
Optimal Block-Level Draft Verification paper update

### ISSUE THREAD

**Issue by poedator** [hemingkx/SpeculativeDecodingPapers#5]
Hi, thanks for maintaining the list!

I noticed that the paper
Optimal Block-Level Draft Verification for Accelerating Speculative Decoding
Ziteng Sun, Jae Hun Ro, Ahmad Beirami, Ananda Theertha Suresh. [[pdf](https://arxiv.org/pdf/2403.10444.pdf)], 2024.03.

is now named "Block Verification Accelerates Speculative Decoding" with slightly different authors list. Same URL.

**Comment by hemingkx** [comment]
Thanks for the reminder! The paper information will be updated.
