### ISSUE TITLE
The code of "Parallel Speculative Decoding with Adaptive Draft Length" has released

### ISSUE THREAD

**Issue by smart-lty** [hemingkx/SpeculativeDecodingPapers#6]
Thanks for your great work! Could you please update some resources to our paper "Parallel Speculative Decoding with Adaptive Draft Length"? I have attached a link to our blog and codebase below for your convenience.

paper: https://arxiv.org/abs/2408.11850
blog: https://pearl-code.github.io/
code: https://github.com/smart-lty/ParallelSpeculativeDecoding

**Comment by hemingkx** [comment]
Sure! Thx for your up-to-date info!
